version: '3'

services:

  logstash:
    command: /usr/share/plugins/plugin/.ci/logstash-run.sh
    environment:
        - INTEGRATION=${INTEGRATION:-false}
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
        - ES_SSL_SUPPORTED_PROTOCOLS=$ES_SSL_SUPPORTED_PROTOCOLS
  elasticsearch:
    build:
      context: ../
      dockerfile: .ci/Dockerfile.elasticsearch
      args:
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
        - INTEGRATION=${INTEGRATION:-false}
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
    environment:
      #- ELASTIC_PASSWORD=$ELASTIC_PASSWORD a user is setup manually
      - xpack.security.enabled=${SECURE_INTEGRATION:-false}
      - ES_SSL_SUPPORTED_PROTOCOLS=$ES_SSL_SUPPORTED_PROTOCOLS
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms640m -Xmx640m
    tty: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    user: elasticsearch

